- name: my play 1
  gather_facts: false
  hosts: web_servers
  tasks:
  - name: mytask1
    apt:
      update_cache: true
  - name: mytask2
    apt:
     name: nginx
     state: latest
  - name: mytask3
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
  - name: mytask4
    ansible.builtin.sysvinit: #because the contasiner is using SysV not systemd
      name: nginx
      state: restarted
      enabled: yes