  - name: copy
    copy:
      src: "{{ item }}"
      dest: /var/www/html/{{ item }}
    loop: "{{ my_files }}"
    notify: dynamic

  - name: dynamic
    template:
      src: index.html.j2
      dest: /var/www/html/index.html.j2
    notify: restart

  - name: restart
    ansible.builtin.sysvinit:
     name:  "{{ package_name }}"
     state: restarted
     enabled: yes